### PR TITLE
Improve regex

### PR DESCRIPTION
**Pull request by irazasyed**
This will match `window.location = '*'`

One of the sites has this type of redirect and I was going through your code and revised the regex a bit (Tho, I'm not so good with regex -- Please feel free to change but would be great if we could support the above pattern).

### CODE REVIEW

**Comment by willwashburn** [comment]
Cool -- thanks. I need to look into why the tests are failing here. Also this would be a good candidate to add in the different cases you're referring to!

**Comment by irazasyed** [comment]
There is some error: `The command "phpenv global 5.4" failed and exited with 1 during .`

**Comment by willwashburn** [comment]
@irazasyed doesn't window.location="*" just redirect to the page you're on? With respect to discovering the canonical url we don't need to do that right? It's just the page we're already on?

**Comment by irazasyed** [comment]
But it's a JS redirect which `mushroom` doesn't follow! If it was following, then yes. But since it doesn't, we extract the final destination URL from JS.

I have a site that is basically a link tracker for stats that uses JS redirect. The destination URL is within the `window.location="*"`

**Comment by willwashburn** [comment]
Sorry, I'm still not following -- Can you share an example? Sounds like maybe we should fix Mushroom then instead of this parsing (since, I believe, * would then break Mushroom)?

**Comment by willwashburn** [comment]
Also, I appreciate you taking the time -- I might just be missing it!

**Comment by irazasyed** [comment]
Please try this example and go through the explanation I've given [here](https://gist.github.com/irazasyed/ca4754439beda263a1e0a88b907be5cb).

That should help you understand why this change is required. You may have to import the autoloader or try the snippet in your exiting test/local setup.

**Comment by irazasyed** [comment]
@willwashburn Were you able to check the example? Please let me know if you have any Qs.

**Comment by irazasyed** [comment]
@willwashburn Just following up to see if we could get this merged, please?

**Comment by willwashburn** [comment]
Took me awhile, but I finally understood what was going on here. Your change makes a lot of sense. Thanks for your patience!

I've tagged 3.1.3 which should now be in mushroom as well.

**Comment by irazasyed** [comment]
Awesome! 

Thanks for merging. Appreciated :)

**Pull request merged**
